import type { Metadata } from "next";
import "./globals.css";
import "./scrollBar.css"
import { Providers } from "./providers";
import { ApiProvider } from "@/contexts/api";
import { StateProvider } from "@/contexts/state";
import LayoutPage from "@/layouts/layout";


export const metadata: Metadata = {
  title: "Tech-film",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Jersey+10&display=swap" rel="preload" />
        <link
          data-react-helmet="true"
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Fjalla+One&family=PT+Sans+Narrow:wght@700&display=swap"
        />
        <link
          data-react-helmet="true"
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Honk&family=Press+Start+2P&family=Protest+Revolution&display=swap"
        />
        <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap"
          data-react-helmet="true"
          rel="preload"
        />
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
        />
        <link href="https://fonts.cdnfonts.com/css/sabre-shark" rel="stylesheet" />
      </head>
      <body>
        <StateProvider>
          <ApiProvider>
            <Providers>
              <LayoutPage>{children}</LayoutPage>
            </Providers>
          </ApiProvider>
        </StateProvider>
      </body>
    </html>
  );
}
